In [5]:
from vectors import *

def plane_equation(p1,p2,p3):
    paralle1 = subtract(p2, p1)
    paralle2 = subtract(p3, p1)
    a,b,c = cross(paralle1, paralle2)
    d = dot((a,b,c), p1)
    return a,b,c,d

In [7]:
plane_equation((1,1,1), (3,0,0), (0,3,0))

(3, 3, 3, 9)

In [25]:
import numpy as np
matrix = np.array(((1,1,1,0,0), (0,0,0,0,1), (0,1,0,0,0), (0,0,0,1,0), (1,0,0,0,0)))
vector = np.array((-2,3,1,-1,0))

In [27]:
np.linalg.solve(matrix, vector)

array([ 0.,  1., -3., -1.,  3.])

In [29]:
matrix = np.array(((1,1,-1),(0,2,-1), (1,0,1)))
inv_matrix = np.linalg.inv(matrix)

In [31]:
inv_matrix

array([[ 0.66666667, -0.33333333,  0.33333333],
       [-0.33333333,  0.66666667,  0.33333333],
       [-0.66666667,  0.33333333,  0.66666667]])

In [33]:
vector = np.array((-1,3,2))

In [35]:
np.matmul(inv_matrix, vector)

array([-1.,  3.,  3.])